import Footer from "../components/footer/Footer";
import Navbar from "../components/navbar/Navbar";
import { ThemeProvider } from "../context/ThemeContext";
import "./globals.css";
import { Inter, Roboto } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["100", "300", "400", "500", "700", "900"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className + "  bg-slate-950 text-gray-200 overflow-x-hidden"}>
        <ThemeProvider>
          <div className="container mx-auto min-h-screen flex flex-col justify-between">
            <Navbar />
            {children}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
